apiVersion: v1
kind: Service

metadata:
  name: demo-fastapi-service

spec:
  selector:
    app: demo-fastapi

  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}

  type: {{ .Values.service.type }}